default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: development_bucketlist
  
test:
  <<: *default
  database: test_bucketlist

production:
  <<: *default
  database: production_bucketlist
